on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set output filename
        id: set-chrome-filename
        run: echo "FILENAME=treetop-chrome-${GITHUB_REF#refs/*/}.zip" >> $GITHUB_OUTPUT
      - name: Set output filename
        id: set-firefox-filename
        run: echo "FILENAME=treetop-firefox-${GITHUB_REF#refs/*/}.zip" >> $GITHUB_OUTPUT
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: TREETOP_TARGET=chrome npm run build
      - run: TREETOP_TARGET=firefox npm run build
      - run: npx web-ext build --source-dir dist/chrome --no-input --filename "${{ steps.set-chrome-filename.outputs.FILENAME}}"
      - run: npx web-ext build --source-dir dist/firefox --no-input --filename "${{ steps.set-firefox-filename.outputs.FILENAME}}"
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./web-ext-artifacts/*.zip
          artifactContentType: application/zip
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
